# Ejercicio Practico: Multiplicacion y Aritmetica Matricial

Hugo J. Rodas


17006259

In [15]:
import numpy as np

### Multiplicación Matricial 

Una de las operaciones mas importantes tanto en matemáticas como en ciencias de la computación y ciencia de datos y también una de las mas comunes es la multiplicación matricial, que podemos conceptualizar de 2 maneras:

* **Matriz por vector**
* **Matriz por matriz**

Esta es una operación sumamente utilizada e importante y es diferente de las que hasta ahora habiamos visto: **operaciones elemento por elemento** por lo cual NO ES IGUAL QUE EL PRODUCTO HADAMARD.

El producto matricial **AxB** solo esta definido para pares de matrices que cumplen con la propiedad de que el número de columnas de A sea igual que el número de filas de B. El resultado es una nueva matriz cuyo numero de filas es igual al número de filas de A y el número de columnas es igual al número de columnas de B

<img src="https://www.geogebra.org/resource/jyFms9hh/gWfr05GxoKt6c3JS/material-jyFms9hh.png">

La forma de calcular la multiplicación matricial AxB se basa en el producto punto, para la matriz de resultado C el elemento en la fila "i" y columna "j" consiste en el producto punto entre la fila "i" de A y la columna "j" de B.

Por lo cual contrario a lo que muchos creen, la multiplicación matricial **NO ES LO MISMO QUE EL PRODUCTO PUNTO** pero si lo utiliza ,la matriz resultante es una matriz de productos punto.

<img src="https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg">

In [37]:
A = np.array([[1,2],   #matriz 2x2
              [3,4]])
B = np.array([[1],    # vector 2x1
              [2]])

np.matmul(A,B) #numero de cols de A debe ser igual al numero de filas de B ,resultado 2x1

array([[ 5],
       [11]])

In [38]:
A = np.array([[1,2], #matriz de 3x2
              [4,5],
              [7,8]])
B = np.array([[1,2,3], #matriz de 2x3
              [0,5,2]])

np.matmul(A,B) #resutlado de 3x3

array([[ 1, 12,  7],
       [ 4, 33, 22],
       [ 7, 54, 37]])

In [39]:
A = np.array([[1,2,3], #matriz 2x3
              [4,5,6]])
B = np.array([[7,8],  #matriz 3x2
              [9,10],
              [11,12]])
C = np.matmul(A,B) #matriz de resultado 2x2

print(C)

[[ 58  64]
 [139 154]]




**Ejemplo en DS** : en inteligencia artificial y ML en la sub-rama "reinforcement learning" la "ecuacion de bellman" puede aplicarse de manera vectorizada a traves del operar vectores, matrices y escalares en una sola expresion.

<img src="https://rebornhugo.github.io/assets/images/post_images/%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A02/bellman%20equation2.PNG">

* n = numero de estados del sistema.
* V(s) = vector que representa el valor esperado para cierto estado
* R = recompensa inmediata percibida por el agente al salir de cierto estado.(vector)
* P = matriz de transicion de la cadena de Markov sub-yacente.(matriz)
* γ = factor de descuento de recompensas futuras(escalar)

Calcular V(s) para el siguiente sistema aplicando la ecuación de bellman de manera vectorizada.

In [30]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99

V_s = R + gamma * np.matmul(P,V)

print(V_s)


[10.  2.  5.]


**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicacion de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producira una nueva matriz con el mismo numero de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la funcion "sigmoid"(descrita a continuacion) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamanio pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la funcion sigmoid. El resultado debe ser un tensor con el mismo numero de filas que la matriz X y una sola columna(una prediccion para cada fila de X

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [16]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [31]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

print(H1_W)
print(OL_W)
print(X)

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1

print(H1)
print(OL)

[[ 0.25 -8.  ]
 [ 0.37 14.  ]]
[[4]
 [9]]
[[0.1 0.2]
 [1.  2. ]]
[[0.52472981 0.88079708]
 [0.72908792 1.        ]]
[[0.99995577]
 [0.99999332]]


### Ejercicio 

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [32]:
def neural_network(X):
    
    HL1 = np.array([0.712,0.112])
    HL2 = np.array([0.355,0.855])
    HL3 = np.array([0.268,0.468])
    OL = np.array([0.116,0.329,0.708])
    N1 = np.matmul(X,HL1)
    N2 = np.matmul(X,HL2)
    N3 = np.matmul(X,HL3)
    
    Hidden_Layer = np.array([N1,N2,N3])
    Hidden_Layer = sigmoid(Hidden_Layer)
    
    Output_Layer = np.matmul(OL,Hidden_Layer)
    Output_Layer = sigmoid(Output_Layer)
    return Output_Layer

prr = np.array([[1,1]])

print(neural_network(prr))

[0.69269553]


In [33]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

print(neural_network(X))

[0.70244573 0.66259284 0.75933678 0.75973948 0.75802295 0.6739704
 0.75954693 0.76005845 0.75952743 0.76005845]


### Broadcasting

Python utiliza un mecanismo conocido como **"broadcasting"** para algunas operaciones cuando el tamaño de los operandos no coincide, por ejemplo el caso de una suma entre una matriz y un vector, broadcasting "expande"(siempre que sea posible) el vector para que tenga la misma forma que la matriz replicando el vector cuantas veces sea necesario para tener la misma forma y luego aplica la operacion **"elementwise"** (elemento a elemento).

Para cuando se trabaja con matrices y una matriz A se opera con algún vector B broadcasting busca replicar o copiar el vector las veces que sea necesario para obtener una matriz del mismo tamaño , por ejemplo si se tiene una matriz de tamaño 4x5 , y un vector de 4 elementos, broadcasting creará una matriz que consiste en copiar el vector de 4 elementos 5 veces.

Broadcasting no funciona en casos donde las dimensiones no son compatibles, por ejemplo para el caso anterior, broadcasting no  hubiera funcionado si el vector tuviera 3 elementos y hubiera resultado en un error: **operands could not be broadcast together with shapes ... **

* https://www.youtube.com/watch?v=YrOrAcMjFB4
* https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [40]:
matriz = np.array([[1,2,3,10],  #matriz de 3x4
                   [4,5,6,11],
                   [7,8,9,12]])
colum_vector = np.array(  # vector orientado columnarmente
                  [1,
                   2,
                   3]).reshape((3,1))
row_vector = np.array([1,2,3,4]).reshape((1,4)) # vector orientado por filas

In [41]:
print(matriz.shape)
print(colum_vector.shape)
print(row_vector.shape)

(3, 4)
(3, 1)
(1, 4)


In [42]:
matriz + colum_vector #operación no definida matemáticamente pero posible con broadcasting

array([[ 2,  3,  4, 11],
       [ 6,  7,  8, 13],
       [10, 11, 12, 15]])

In [43]:
matriz + row_vector #operación no definida matemáticamente pero posible con broadcasting

array([[ 2,  4,  6, 14],
       [ 5,  7,  9, 15],
       [ 8, 10, 12, 16]])

In [44]:
matriz - colum_vector #operación no definida matemáticamente pero posible con broadcasting 

array([[0, 1, 2, 9],
       [2, 3, 4, 9],
       [4, 5, 6, 9]])

In [45]:
matriz * row_vector #operación no definida matemáticamente pero posible con broadcasting

array([[ 1,  4,  9, 40],
       [ 4, 10, 18, 44],
       [ 7, 16, 27, 48]])

In [46]:
colum_vector = np.array(  # vector orientado columnarmente
                  [1,
                   2,
                   3,
                   4]).reshape((4,1))
# la siguiente linea intentaa operar una matriz de 3x4 con un vector incompatible de 4x1 resultando en error
#matriz + colum_vector

### Funciones miscelaneas(agregación y estadistica descriptiva básica) 

Ya hemos trabajado algunas funciones de NumPy pero han sido funciones "elementwise" cuyo vector resultante tiene el mismo tamaño que el vector de entrada, existen muchas otras funciones que utilizamos en casos en los que necesitamos agregar,resumir cierta matriz,incluyendo en este tipo de funciones algunas de estadistica descriptiva básica.

En esta sección estudiamos funciones ya estudiadas previamente con vectores ,pero como veremos podemos configurar su comportamiento para lograr comportamientos específicos para matrices.

Podemos utilizar un segundo parámetro llamado **axis** para especificar sobre que dimensión o eje del vector queremos operar, para el caso de matrices podemos hacerlo por:

* axis = 0 : filas,calcula la función deseada a traves de filas y devuelve para cada columna un resultado, el resultado es un vector cuyo tamaño es igual al numero de columnas de la matriz original.
* axis = 1 : columnas,calcula la función deseada a traves de columnas ,y devuelve para cada fila un resultado,el resultado es un vector cuyo tamaño es igual al numero de de filas de la matriz original.
* axis = None: si especificamos axis = None ( o no lo especificamos) el  comportamiento es similar al caso de vectores, se obtiene un único resultado(escalar) para todo el tensor

<img src="https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/numpy-arrays-have-axes.png">

<img src="https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2018/12/numpy-axes-np-sum-axis-0.png">

In [47]:
x = np.array([[1,2,3,4,5],
              [6,7,8,9,2]])

x_nan = np.array([[1,2,3,4,np.nan],
                  [6,8,2,2,16]])

Si no especificamos el parametro axis, el comportamiento es similar al obtenido con vectores.

In [48]:
print(np.max(x))
print(x.max())
print(np.max(x_nan))
print(np.nanmax(x))
print(np.nanmax(x_nan))

9
9
nan
9
16.0


In [49]:
#al usar axis con matrices que contienen nan se obtiene nan solo en la fila o columna que posea valores nan
#siimlar al caso de vectores podemos usar nanmax para ignorar nans

print("Maximo de cada fíla de x a traves de las columnas:")
print(np.max(x,axis = 1))
print("Maximo de cada cada columna de x a traves de las filas:")
print(x.max(axis=0))
print("Maximo de cada cada columna de x_nan a traves de las filas:")
print(np.max(x_nan,axis=0))
print("Maximo ignorando nans de cada fíla de x a traves de las columnas:")
print(np.nanmax(x,axis=1))
print("Maximo de cada fila a traves de columnas de x_nan,ignorando nans:")
print(np.nanmax(x_nan,axis=1))

Maximo de cada fíla de x a traves de las columnas:
[5 9]
Maximo de cada cada columna de x a traves de las filas:
[6 7 8 9 5]
Maximo de cada cada columna de x_nan a traves de las filas:
[  6.   8.   3.   4.  nan]
Maximo ignorando nans de cada fíla de x a traves de las columnas:
[5 9]
Maximo de cada fila a traves de columnas de x_nan,ignorando nans:
[  4.  16.]


In [50]:
#al usar axis con matrices que contienen nan se obtiene nan solo en la fila o columna que posea valores nan
#siimlar al caso de vectores podemos usar nanmin para ignorar nans

print("Minimo general de la matriz x:")
print(np.min(x))
print("Minimo general ignorando valores nan de la matriz x_nan:")
print(np.argmin(x_nan))
print("Minimo de cada fíla de x a traves de las columnas:")
print(np.min(x,axis = 1))
print("Minimo de cada cada columna de x a traves de las filas:")
print(x.min(axis=0))
print("Minimo de cada cada columna de x_nan a traves de las filas:")
print(np.min(x_nan,axis=0))
print("Minimo ignorando nans de cada fíla de x a traves de las columnas:")
print(np.nanmin(x,axis=1))
print("Minimo de cada fila a traves de columnas de x_nan,ignorando nans:")
print(np.nanmin(x_nan,axis=1))

Minimo general de la matriz x:
1
Minimo general ignorando valores nan de la matriz x_nan:
4
Minimo de cada fíla de x a traves de las columnas:
[1 2]
Minimo de cada cada columna de x a traves de las filas:
[1 2 3 4 2]
Minimo de cada cada columna de x_nan a traves de las filas:
[  1.   2.   2.   2.  nan]
Minimo ignorando nans de cada fíla de x a traves de las columnas:
[1 2]
Minimo de cada fila a traves de columnas de x_nan,ignorando nans:
[ 1.  2.]


#### argmax y argmin para matrices

Al estudiar vectores las funciones argmax y argmin nos proveian una forma de encontrar la posición(o indice) del valor máximo o mínimo del vector. Para matrices debemos especificar el comportamiento deseado nuevamente a través del parametro axis, cuando este es 0 o 1 el comportamiento es similar al ya visto previamente, pero cuando este no es especificado o se usa el valor None necesitamos poner atención al comportamiento: **La matriz es interpretada como un vector obtenido al colapsar todas las filas de la matriz** y argmax,argmin se comportarán como si se aplicaran sobre este vector.

In [51]:
x = np.array([[4,6,9],
              [2,1,11]])
print(x)

[[ 4  6  9]
 [ 2  1 11]]


In [52]:
print(np.argmin(x,axis=0))
print(x.min(axis=0))

[1 1 0]
[2 1 9]


In [53]:
print(np.argmax(x,axis=1))
print(x.max(axis=1))

[2 2]
[ 9 11]


In [54]:
print(np.argmin(x),np.argmax(x))

4 5


El resultado de aplicar argmin y argmax sobre la matriz sin especificar el axis es equivalente a el siguiente código:

In [55]:
x_vector = np.reshape(x,-1)

x_vector

array([ 4,  6,  9,  2,  1, 11])

In [56]:
print(np.argmin(x_vector),np.argmax(x_vector))

4 5


#### suma,producto(normal y acumulativa) para matrices.

Nuevamente tenemos en el caso de matrices funciones que también existian en vectores y que pueden ser configuradas para trabajar a través de filas,columnas o general a través del parámetro axis, en este caso tratamos con suma y producto a través de las filas(axis=0), columnas(axis=1) o sobre toda la matriz(axis=None)

In [57]:
x = np.array([[4,6,9],
              [2,1,11]])
print(x)

[[ 4  6  9]
 [ 2  1 11]]


In [58]:
print("Dos formas de obtener la suma de todos los elementos de la matriz x:")
print(np.sum(x))
print(x.sum())
print("Si aplicamos sum() sobre una matriz con al menos un elemento 'nan' el resultado es nan:")
print(np.sum(x_nan))
print("Para ignorar valores 'nan' y sumar el resto podemos usar nansum() en lugar de sum():")
print(np.nansum(x_nan))

Dos formas de obtener la suma de todos los elementos de la matriz x:
33
33
Si aplicamos sum() sobre una matriz con al menos un elemento 'nan' el resultado es nan:
nan
Para ignorar valores 'nan' y sumar el resto podemos usar nansum() en lugar de sum():
44.0


In [59]:
print(np.sum(x,axis=0))
print(x.sum(axis=1))
print(np.sum(x_nan,axis=0))
print(np.nansum(x_nan,axis=1))

[ 6  7 20]
[19 14]
[  7.  10.   5.   6.  nan]
[ 10.  34.]


In [60]:
print(np.prod(x))
print(x.prod())
print(np.prod(x_nan))
print(np.nanprod(x_nan))

4752
4752
nan
73728.0


## Variables categoricas/discretas

Hasta ahora hemos trabajado con numpy exclusivamente usando variables numericas y continuas y hemos dejado por un lado variables categoricas y/o discretas ,pero es necesario tambien poder trabajar con este tipo de variables ya que estan presentes en muchos problemas y por lo tanto en muchos sets de datos.

La razon por la cual hemos dejado de lado estas ,es que en programacion numerica/cientifica(y por lo tanto en ciencia de datos) las variables categoricas y discretas son de cualquier manera convertidas a un equivalente numerico  y este equivalente numerico es usado posteriormenta para analisis,modelado,simulacion, etc. 

La representacion numerica equivalente para una variable categorica  se llama de manera general : **embedding** , y hay multiples tipos de embedding asi como formas y metodos de calcularlos, una familia muy comun es la familia **2vec** por ejemplo:

* **word2vec** : convierte una palabra a un vector.
* **sentence2vec**: convierte una oracion o frase en un vector.
* **doc2vec** : convierte un documento completo en un vector.

<img src = "https://cdn-images-1.medium.com/max/2400/1*2r1yj0zPAuaSGZeQfG6Wtw.png">

<img src ="https://samyzaf.com/ML/nlp/word2vec2.png">

<img src ="https://cdn-images-1.medium.com/max/1600/1*e9fy52nkSy9A9AIN3WZSpw.png">


Debido a la influencia y alta relacion entre ciencia de datos,machine learning, etc y ciencias basicas como matematica y estadistica , es comun toparse con otros terminos con origen estadistico ,por ejemplo: **variables dummy** que nos llevan a la misma idea: **una representacion numerica de una variable categorica y/o discreta**.

En data science y machine learning, el tipo mas comun y conocido es:

### one-hot encoding

One-hot encoding consiste en convertir una variable categorica a un vector de 0s y 1s, el vector tiene tantos elementos como posibles valores pueda tomar la variable y se asigna 1 a la posicion del vector que representa la categoria "presente" en cierta observacion y 0 en el resto. Esto queda mejor explicado bajo un ejemplo:

<img src="https://cdn-images-1.medium.com/max/1600/0*T5jaa2othYfXZX9W.">

<img src="https://naadispeaks.files.wordpress.com/2018/04/mtimfxh.png?w=471&h=151">

La implementacion en Python puede hacerse de diversas formas y hay paquetes como Tensorflow o Pytorch que nos permiten  hacerlo sobre sus tensores usando funciones pre-definidas, cuando se usa NumPy podemos auxiliarnos  de una matriz identidad para lograrlo.

In [66]:
categorias = ["manzana","pollo","brocoli"]
numero_categorias = len(categorias)

numero_categoria = np.array([0,1,2])
categoria_one_hot = np.identity(numero_categorias)[numero_categoria]

print("Vector con numero de categoria:")
print(numero_categoria)
print("Equivalente one-hot encoding:")
print(categoria_one_hot)

Vector con numero de categoria:
[0 1 2]
Equivalente one-hot encoding:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [67]:
categorias = ["rojo","amarillo","verde"]
numero_categorias = len(categorias)

numero_categoria = np.array([0,0,1,2,1])
categoria_one_hot = np.identity(numero_categorias)[numero_categoria]

print("Vector con numero de categoria:")
print(numero_categoria)
print("Equivalente one-hot encoding:")
print(categoria_one_hot)

Vector con numero de categoria:
[0 0 1 2 1]
Equivalente one-hot encoding:
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
