## Tarea: Investigación: np.matrix vs np.ndarray

### Definicion y dimensiones que pueden manejar:

Un **np.ndarray** es una estructura de datos del mismo tipo y puede ser de dimensiones de 1 en adelante. Esta indexado por una tupla de enteros no negativos.

Un **np.matrix** es una estructura de datos del mismo tipo y solo puede tener 2 dimensiones. Esta indexado por una tupla de enteros no negativos. No se pueden tener vectores, o es una matriz de una columna, o una matriz de una fila.


In [10]:
import numpy as np

arreglo_1 = np.array([[-1,8,9],[-4,3,1],[0,-1,6]])
matriz_1 = np.matrix([[-1,8,9],[-4,3,1],[0,-1,6]])


print(arreglo_1)
print(matriz_1)

[[-1  8  9]
 [-4  3  1]
 [ 0 -1  6]]
[[-1  8  9]
 [-4  3  1]
 [ 0 -1  6]]


### Con respecto a la multiplicacion:

En un arreglo:
- la muliplicacion  *****  multiplica elemento por elemento

- la funcion **@** es una multiplicacion matricial

En una matriz:
- la muliplicacion *****  es una multiplicacion matricial.

- la funcion **multiply()** multiplica elemento por elemento

In [8]:
print(arreglo_1 * arreglo_1)
print(arreglo_1 @ arreglo_1)


print(np.multiply(matriz_1 ,matriz_1))
print(matriz_1 * matriz_1)

[[ 1 64 81]
 [16  9  1]
 [ 0  1 36]]
[[-31   7  53]
 [ -8 -24 -27]
 [  4  -9  35]]
[[ 1 64 81]
 [16  9  1]
 [ 0  1 36]]
[[-31   7  53]
 [ -8 -24 -27]
 [  4  -9  35]]


### Atributos de Conveniencia

Un np.ndarray tiene un atributo T., que devuelve la transpuesta de la data.

Un np.matrix tiene atributos .H (transpuesta), .I (inversa), y .A (asarray() ) de la matriz.

In [9]:
print("np.array")
print(arreglo_1.T)

print("np.matrix")
print(matriz_1.H)

print(matriz_1.I)

print(matriz_1.A)

np.array
[[-1 -4  0]
 [ 8  3 -1]
 [ 9  1  6]]
np.matrix
[[-1 -4  0]
 [ 8  3 -1]
 [ 9  1  6]]
[[ 0.09090909 -0.27272727 -0.09090909]
 [ 0.11483254 -0.02870813 -0.16746411]
 [ 0.01913876 -0.00478469  0.13875598]]
[[-1  8  9]
 [-4  3  1]
 [ 0 -1  6]]


**Bibliografia:**

- https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use

- https://www.datacamp.com/community/tutorials/python-numpy-tutorial

- http://cs231n.github.io/python-numpy-tutorial/

- https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u